services:
  app:
    build: .
    user: '33'
    volumes:
      - ./data/app:/var/www/data
  
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    environment:
      DOMAINS: '${APP_DOMAIN} -> http://app'
      STAGE: ${LETSENCRYPT_STAGE-local} # Don't use production until staging works
    volumes:
      - ./data/https-portal:/var/lib/https-portal
